# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn server:app --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8008:8000