# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn server:app --host 0.0.0.0'
    #command: bash -c "alembic upgrade head && uvicorn server:app --host 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db:5432/fastapi
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi"]
      interval: 10s
      timeout: 5s
      retries: 5